export const GET_USERS = "GET_USERS";
export const USERS_ERROR = "USERS_ERROR";

export const SET_SIDEBAR_MENU = "SET_SIDEBAR_MENU";
export const REMOVE_SIDEBAR_MENU = "REMOVE_SIDEBAR_MENU";

export const SET_SELECTED_MENU = "SET_SELECTED_MENU";
export const REMOVE_SELECTED_MENU = "REMOVE_SELECTED_MENU";

export const SET_SELECTED_ORDER = "SET_SELECTED_ORDER";
export const REMOVE_SELECTED_ORDER = "REMOVE_SELECTED_ORDER";

export const SET_SELECTED_CATEGORY = "SET_SELECTED_CATEGORY";
export const REMOVE_SELECTED_CATEGORY = "REMOVE_SELECTED_CATEGORY";

export const FETCH_GENRES = "FETCH_GENRES";
export const FETCH_GENRES_ERROR = "FETCH_GENRES_ERROR";

export const FETCH_SEARCH_MOVIE = "FETCH_SEARCH_MOVIE";
export const LOADING_SEARCH_MOVIE = "LOADING_SEARCH_MOVIE";
export const CLEAR_SEARCH_MOVIE = "CLEAR_SEARCH_MOVIE";
export const ERROR_SEARCH_MOVIE = "ERROR_SEARCH_MOVIE";

export const FETCH_DISCOVER_MOVIE = "FETCH_DISCOVER_MOVIE";
export const LOADING_DISCOVER_MOVIE = "LOADING_DISCOVER_MOVIE";
export const CLEAR_DISCOVER_MOVIE = "CLEAR_DISCOVER_MOVIE";
export const ERROR_DISCOVER_MOVIE = "ERROR_DISCOVER_MOVIE";

export const FETCH_POPULAR_MOVIE = "FETCH_POPULAR_MOVIE";
export const LOADING_POPULAR_MOVIE = "LOADING_POPULAR_MOVIE";
export const ERROR_POPULAR_MOVIE = "ERROR_POPULAR_MOVIE";

export const FETCH_TOP_RATED_MOVIE = "FETCH_TOP_RATED_MOVIE";
export const LOADING_TOP_RATED_MOVIE = "LOADING_TOP_RATED_MOVIE";
export const ERROR_TOP_RATED_MOVIE = "ERROR_TOP_RATED_MOVIE";

export const FETCH_UPCOMING_MOVIE = "FETCH_UPCOMING_MOVIE";
export const LOADING_UPCOMING_MOVIE = "LOADING_UPCOMING_MOVIE";
export const ERROR_UPCOMING_MOVIE = "ERROR_UPCOMING_MOVIE";

export const FETCH_TRENDING_TODAY_MOVIE = "FETCH_TRENDING_TODAY_MOVIE";
export const LOADING_TRENDING_TODAY_MOVIE = "LOADING_TRENDING_TODAY_MOVIE";
export const CLEAR_TRENDING_TODAY_MOVIE = "CLEAR_TRENDING_TODAY_MOVIE";
export const ERROR_TRENDING_TODAY_MOVIE = "ERROR_TRENDING_TODAY_MOVIE";

export const FETCH_TRENDING_THISWEEK_MOVIE = "FETCH_TRENDING_THISWEEK_MOVIE";
export const LOADING_TRENDING_THISWEEK_MOVIE = "LOADING_TRENDING_THISWEEK_MOVIE";
export const CLEAR_TRENDING_THISWEEK_MOVIE = "CLEAR_TRENDING_THISWEEK_MOVIE";
export const ERROR_TRENDING_THISWEEK_MOVIE = "ERROR_TRENDING_THISWEEK_MOVIE";

export const FETCH_GENRE_MOVIE = "FETCH_GENRE_MOVIE";
export const LOADING_GENRE_MOVIE = "LOADING_GENRE_MOVIE";
export const CLEAR_GENRE_MOVIE = "CLEAR_GENRE_MOVIE";
export const ERROR_GENRE_MOVIE = "ERROR_GENRE_MOVIE";

